sonar.projectKey=renanpariiz_projeto-individual-renan-pariz
sonar.organization=renanpariiz

sonar.projectName=projeto-individual-renan-pariz
sonar.projectVersion=1.0

sonar.sources=server,game
sonar.exclusions=**/node_modules/**,**/*.test.js,**/fuzz.test.js

sonar.tests=server
sonar.test.inclusions=**/*.test.js,**/fuzz.test.js

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
