apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mk-game
type: Opaque
stringData:
  user: gces_user
  password: gces_senha
  url: postgres://gces_user:gces_senha@postgres:5432/mk_game_db
